Flipping a coin

**Importing scipy.stats library and using bernoulli**

In [1]:
#Generate rvs for random variates using arg. p for success prob. and  size for no. of coin flips.

from scipy.stats import bernoulli
bernoulli.rvs(p=0.5, size=1)

#The output for the first time is "0" which means failure or T
#If you run it again it will be "array([1])" whch means success or H. 

array([0])

**Change the size of flips**

**Flipping multiple coins**

In [2]:
bernoulli.rvs (p=0.5, size=10)

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 0])

**Checking the number of heads**

In [8]:
sum(bernoulli.rvs(p=0.5, size=10)) #5 heads and 5 tails

5

In [ ]:
sum((bernoulli.rvs(p=0.5, size=10))) #2 heads and 8 tails

2

**Using binomial distribution and binom object**


1.   n => No. of the coin flips
2.   p => Probability of success
3.   size => No. of draws of the same experiment



**Binomial r.v.**

In [ ]:
from scipy.stats import binom
binom.rvs (n=10 , p = 0.5 , size = 1)
#7 heads out of 10 flips

array([7])

**Many draws**

In [ ]:
binom.rvs(n=10, p=0.5 , size=10) #6 is the result that repeats the most for a fair coin.

array([6, 5, 6, 6, 7, 6, 4, 6, 5, 6])

**Biased coin draws**

In [ ]:
binom.rvs(n=10, p=0.3 , size=10) #changed the p= 0.3 (diff. outcomes)

array([2, 5, 3, 4, 2, 4, 1, 4, 2, 5])

**Random number generator seed**



*   To simulate the outcome of a random experiment.
*   If you run the same command with the same random seed, you will always get the same result. In Python we need to set a seed for the generator to produce similar outcomes in each experiment. Then we can check if the results are what we expected. We have two options to configure the generator: using the (**random_state**) parameter of the rvs function or using (**np.random.seed**).


In [9]:
from scipy.stats import binom
binom.rvs(n=10, p=0.5 , size =1, random_state=42)

array([4])

In [10]:
import numpy as np
np.random.seed(42)


In [11]:
from scipy.stats import binom
import numpy as np
np.random.seed(42)
binom.rvs(n=10,p=0.5,size=1)

array([4])

**Practice**

**Flipping coins**

---




This exercise requires the bernoulli object from the scipy.stats library to simulate the two possible outcomes from a coin flip, 1 ("heads") or 0 ("tails"), and the numpy library (loaded as np) to set the random generator seed.

You'll use the bernoulli.rvs() function to simulate coin flips using the size argument.

You will set the random seed so you can reproduce the results for the random experiment in each exercise.

From each experiment, you will get the values of each coin flip. You can add the coin flips to get the number of heads after flipping 10 coins using the sum() function.


---


*Steps:*
1. Import bernoulli from scipy.stats, set the seed with np.random.seed(). Simulate 1 flip, with a 35% chance of heads.
2. Use bernoulli.rvs() and sum() to get the number of heads after 10 coin flips with 35% chance of getting heads.
3. Using bernoulli.rvs() and sum(), try to get the number of heads after 5 flips with a 50% chance of getting heads.

In [ ]:
# Import numpy
import numpy as np
# Import the bernoulli object from scipy.stats
from scipy.stats import bernoulli

# Set the random seed to reproduce the results
np.random.seed(42)

# Simulate one coin flip with 35% chance of getting heads
coin_flip = bernoulli.rvs(p=0.35, size=10)
print(coin_flip)

[0 1 1 0 0 0 0 1 0 1]


In [ ]:
#Using bernoulli.rvs() and sum(), try to get the number of heads after 5 flips with a 50% chance of getting heads.
five_coin_flips = bernoulli.rvs(p=0.5, size=5)
coin_flips_sum = sum(five_coin_flips)
print(coin_flips_sum)

2


**Using binom to flip even more coins
Previously, you simulated 10 coin flips with a 35% chance of getting heads using bernoulli.rvs().**

**This exercise loads the binom object from scipy.stats so you can use binom.rvs() to simulate 20 trials of 10 coin flips with a 35% chance of getting heads on each coin flip.**

In [ ]:
#Defining binom
# Set the random seed to reproduce the results
np.random.seed(42)

# Simulate 20 trials of 10 coin flips 
draws = binom.rvs(n=10, p=0.35, size=20)
print(draws)

[3 6 4 4 2 2 1 5 4 4 1 6 5 2 2 2 3 4 3 3]
